const ingredients = [
  {
    id: 0,
    name: 'Dough',
    img: './img/0.png',
    preview: './img/0.1.png',
    type: 'basic',
    added: true,
    price: 3,
  },
  {
    id: 1,
    name: 'Marinara',
    img: './img/1.png',
    preview: './img/1.1.png',
    type: 'sauce',
    added: false,
    price: 0.75,
  },
  {
    id: 2,
    name: 'Hot Sauce',
    img: './img/2.png',
    preview: './img/2.1.png',
    type: 'sauce',
    added: false,
    price: 0.6,
  },
  {
    id: 3,
    name: 'BBQ Sauce',
    img: './img/3.png',
    preview: './img/3.1.png',
    type: 'sauce',
    added: false,
    price: 0.5,
  },
  {
    id: 4,
    name: 'Alfredo',
    img: './img/4.png',
    preview: './img/4.1.png',
    type: 'sauce',
    added: false,
    price: 0.75,
  },
  {
    id: 5,
    name: 'Mozzarella',
    img: './img/5.png',
    preview: './img/5-6-7.png',
    type: 'cheese',
    added: false,
    price: 1.5,
  },
  {
    id: 6,
    name: 'Extra Mozzarella',
    img: './img/6.png',
    preview: './img/5-6-7.png',
    type: 'cheese',
    added: false,
    price: 2.0,
  },
  {
    id: 7,
    name: 'So Much Mozzarella',
    img: './img/7.png',
    preview: './img/5-6-7.png',
    type: 'cheese',
    added: false,
    price: 3.0,
  },
  {
    id: 8,
    name: 'Parmesan',
    img: './img/8.png',
    preview: './img/8.1.png',
    type: 'cheese',
    added: false,
    price: 2.5,
  },
  {
    id: 9,
    name: 'Cheddar',
    img: './img/9.png',
    preview: './img/9-10.png',
    type: 'cheese',
    added: false,
    price: 3.0,
  },
  {
    id: 10,
    name: 'Extra Cheddar',
    img: './img/10.png',
    preview: './img/9-10.png',
    type: 'cheese',
    added: false,
    price: 4.0,
  },

  {
    id: 11,
    name: 'Pepperoni',
    img: './img/11.png',
    preview: './img/11.1.png',
    type: 'topping',
    added: false,
    price: 2.5,
  },
  {
    id: 12,
    name: 'Sausage',
    img: './img/12.png',
    preview: './img/12.1.png',
    type: 'topping',
    added: false,
    price: 2.0,
  },
  {
    id: 13,
    name: 'Pineapple',
    img: './img/13.png',
    preview: './img/13.1.png',
    type: 'topping',
    added: false,
    price: 0.75,
  },
  {
    id: 14,
    name: 'Peppers',
    img: './img/14.png',
    preview: './img/14.1.png',
    type: 'topping',
    added: false,
    price: 1.0,
  },
  {
    id: 15,
    name: 'Onions',
    img: './img/15.png',
    preview: './img/15.1.png',
    type: 'topping',
    added: false,
    price: 1.5,
  },
  {
    id: 16,
    name: 'Tomatoes',
    img: './img/16.png',
    preview: './img/16.1.png',
    type: 'topping',
    added: false,
    price: 1.75,
  },
  {
    id: 17,
    name: 'Spinach',
    img: './img/17.png',
    preview: './img/17.1.png',
    type: 'topping',
    added: false,
    price: 0.75,
  },
  {
    id: 18,
    name: 'Mushrooms',
    img: './img/18.png',
    preview: './img/18.1.png',
    type: 'topping',
    added: false,
    price: 2.75,
  },
  {
    id: 19,
    name: 'Black Olives',
    img: './img/19.png',
    preview: './img/19.1.png',
    type: 'topping',
    added: false,
    price: 1.6,
  },
  {
    id: 20,
    name: 'Ham',
    img: './img/20.png',
    preview: './img/20.1.png',
    type: 'topping',
    added: false,
    price: 2.6,
  },
  {
    id: 21,
    name: 'Bacon',
    img: './img/21.png',
    preview: './img/21.1.png',
    type: 'topping',
    added: false,
    price: 3.0,
  },
  {
    id: 22,
    name: 'Chicken',
    img: './img/22.png',
    preview: './img/22.1.png',
    type: 'topping',
    added: false,
    price: 2.5,
  },
];

export default ingredients;
